/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ChooseButton: typeof import('./../src/components/ChooseButton.vue')['default']
    Feedback: typeof import('./../src/components/Feedback.vue')['default']
  }
}
